$( document ).ready(function() {
    $('.say-slider-section').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        responsive:{
            767:{
                items:1
            },
            991:{
                items:2
            },
            1200:{
                items:3
            }
        }
    })
    $('.popular-courses-slider').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        responsive:{
            767:{
                items:1
            },
            991:{
                items:2
            },
            1200:{
                items:3
            }
        }
    })
});
